import {
  BorderStyle,
  Document,
  ExternalHyperlink,
  HeadingLevel,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
  type IParagraphOptions,
} from 'docx'
import { parseInline } from './md-inline'
import type { LegalBlock, LegalDocument, LegalSection } from './types'

// LegalDocument → DOCX (Buffer).
//
// The docx package has a declarative tree of Document → Paragraph / Table
// nodes with TextRun / ExternalHyperlink inline children. We map each
// LegalBlock kind to the corresponding docx primitive; inline MD tokens
// become TextRun(bold/italic) or ExternalHyperlink + TextRun (links).

const COLORS = {
  navy: '0F2D5B',
  teal: '0D7A6B',
  ink: '0B1A35',
  ink2: '43506B',
  ink3: '6B7A93',
  line: 'E5E9EF',
  tealLight: 'E0F4F1',
}

export async function serializeToDocx(doc: LegalDocument): Promise<Buffer> {
  const children: Paragraph[] = []

  // Title
  children.push(
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [
        new TextRun({
          text: stripTrailingPeriod(doc.title),
          bold: true,
          color: COLORS.navy,
          size: 44,
        }),
      ],
      spacing: { after: 200 },
    }),
  )

  // Lede
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: doc.lede, color: COLORS.ink2, size: 22 }),
      ],
      spacing: { after: 300 },
    }),
  )

  // Meta
  const tablesAndParas: (Paragraph | Table)[] = [...children]
  tablesAndParas.push(metaTable(doc.meta))
  tablesAndParas.push(new Paragraph({ text: '', spacing: { after: 200 } }))

  // TOC
  tablesAndParas.push(
    new Paragraph({
      children: [
        new TextRun({
          text: 'CONTENTS',
          bold: true,
          color: COLORS.ink3,
          size: 18,
        }),
      ],
      spacing: { after: 120 },
    }),
  )
  doc.tocItems.forEach((t, i) => {
    tablesAndParas.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `${(i + 1).toString().padStart(2, '0')}.  `,
            color: COLORS.ink3,
            size: 20,
          }),
          new TextRun({ text: t.label, color: COLORS.ink2, size: 20 }),
        ],
        spacing: { after: 40 },
      }),
    )
  })
  tablesAndParas.push(new Paragraph({ text: '', spacing: { after: 300 } }))

  // Intro
  if (doc.intro) {
    for (const p of doc.intro) {
      tablesAndParas.push(paragraph(p, { size: 22 }))
    }
  }

  // Sections
  doc.sections.forEach((s, idx) => {
    tablesAndParas.push(...renderSection(s, idx + 1))
  })

  // Addendum
  if (doc.addendum) {
    const a = doc.addendum
    tablesAndParas.push(
      new Paragraph({
        text: '',
        border: {
          bottom: {
            color: COLORS.line,
            space: 1,
            style: BorderStyle.SINGLE,
            size: 6,
          },
        },
        spacing: { before: 400, after: 300 },
      }),
    )
    tablesAndParas.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [
          new TextRun({
            text: a.label,
            bold: true,
            color: COLORS.navy,
            size: 36,
          }),
        ],
        spacing: { after: 200 },
      }),
    )

    if (a.tocItems.length > 0) {
      tablesAndParas.push(
        new Paragraph({
          children: [
            new TextRun({
              text: a.tocTitle.toUpperCase(),
              bold: true,
              color: COLORS.ink3,
              size: 18,
            }),
          ],
          spacing: { after: 120 },
        }),
      )
      a.tocItems.forEach((t, i) => {
        tablesAndParas.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `${(i + 1).toString().padStart(2, '0')}.  `,
                color: COLORS.ink3,
                size: 20,
              }),
              new TextRun({ text: t.label, color: COLORS.ink2, size: 20 }),
            ],
            spacing: { after: 40 },
          }),
        )
      })
      tablesAndParas.push(new Paragraph({ text: '', spacing: { after: 200 } }))
    }

    if (a.intro) {
      for (const p of a.intro) {
        tablesAndParas.push(paragraph(p, { size: 22 }))
      }
    }

    a.sections.forEach((s, idx) => {
      tablesAndParas.push(...renderSection(s, idx + 1))
    })
  }

  // `children` above was just Title+lede; replace with the full tree.
  const d = new Document({
    creator: 'ConsentShield',
    title: stripTrailingPeriod(doc.title),
    description: 'Generated by ConsentShield legal downloads pipeline.',
    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 22, color: COLORS.ink },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1080, bottom: 1080, left: 1080, right: 1080 },
          },
        },
        children: tablesAndParas,
      },
    ],
  })

  const buf = await Packer.toBuffer(d)
  return buf
}

function renderSection(
  section: LegalSection,
  number: number,
): (Paragraph | Table)[] {
  const out: (Paragraph | Table)[] = []
  out.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [
        new TextRun({
          text: number.toString().padStart(2, '0'),
          color: COLORS.teal,
          bold: true,
          size: 20,
        }),
        new TextRun({
          text: `   ${section.title}`,
          bold: true,
          color: COLORS.navy,
          size: 28,
        }),
      ],
      spacing: { before: 300, after: 160 },
    }),
  )

  for (const b of section.blocks) {
    out.push(...renderBlock(b))
  }
  return out
}

function renderBlock(block: LegalBlock): (Paragraph | Table)[] {
  switch (block.kind) {
    case 'h3':
      return [
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [
            new TextRun({
              text: block.text,
              bold: true,
              color: COLORS.navy,
              size: 22,
            }),
          ],
          spacing: { before: 160, after: 80 },
        }),
      ]
    case 'p':
      return [paragraph(block.md, { size: 22 })]
    case 'ul':
      return block.items.map((item) => bulletParagraph(item))
    case 'note':
      return [noteParagraph(block.md)]
    case 'contact':
      return contactBlock(block.heading, block.rows)
    case 'subprocTable':
      return [
        simpleTable(
          ['Sub-processor', 'Activity', 'Location'],
          block.rows.map((r) => [r.name, r.activity, r.location]),
          [35, 40, 25],
        ),
        new Paragraph({ text: '', spacing: { after: 160 } }),
      ]
    case 'sccTable':
      return [
        simpleTable(
          ['SCC Clause', 'Election / parameter'],
          block.rows.map((r) => [r.clause, r.value]),
          [35, 65],
        ),
        new Paragraph({ text: '', spacing: { after: 160 } }),
      ]
  }
}

function paragraph(
  md: string,
  runOpts: { size?: number; color?: string } = {},
  paraOpts: Partial<IParagraphOptions> = {},
): Paragraph {
  return new Paragraph({
    ...paraOpts,
    spacing: { after: 160, ...(paraOpts.spacing ?? {}) },
    children: inlineChildren(md, runOpts),
  })
}

function bulletParagraph(md: string): Paragraph {
  return new Paragraph({
    bullet: { level: 0 },
    spacing: { after: 80 },
    children: inlineChildren(md, { size: 22 }),
  })
}

function noteParagraph(md: string): Paragraph {
  return new Paragraph({
    shading: { type: ShadingType.CLEAR, color: 'auto', fill: 'F1F5F9' },
    border: {
      left: {
        color: COLORS.teal,
        space: 6,
        style: BorderStyle.SINGLE,
        size: 12,
      },
    },
    spacing: { before: 160, after: 200 },
    children: inlineChildren(md, { size: 21, color: COLORS.ink2 }),
  })
}

function contactBlock(
  heading: string,
  rows: Array<{ label: string; value: string }>,
): (Paragraph | Table)[] {
  const out: (Paragraph | Table)[] = []
  out.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_3,
      children: [
        new TextRun({
          text: heading,
          bold: true,
          color: COLORS.navy,
          size: 22,
        }),
      ],
      spacing: { before: 200, after: 120 },
    }),
  )
  for (const r of rows) {
    out.push(
      new Paragraph({
        spacing: { after: 60 },
        children: [
          new TextRun({
            text: r.label.toUpperCase() + '   ',
            bold: true,
            color: COLORS.ink3,
            size: 18,
          }),
          ...inlineChildren(r.value, { size: 20 }),
        ],
      }),
    )
  }
  return out
}

function metaTable(
  meta: Array<{ label: string; value: string }>,
): Table {
  const cols = Math.min(meta.length, 4)
  const colPct = Math.floor(100 / cols)
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: {
      top: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      bottom: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      left: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      right: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      insideHorizontal: {
        style: BorderStyle.NONE,
        size: 0,
        color: 'FFFFFF',
      },
      insideVertical: {
        style: BorderStyle.NONE,
        size: 0,
        color: 'FFFFFF',
      },
    },
    rows: [
      new TableRow({
        children: meta.slice(0, cols).map(
          (m) =>
            new TableCell({
              width: { size: colPct, type: WidthType.PERCENTAGE },
              children: [
                new Paragraph({
                  spacing: { after: 40 },
                  children: [
                    new TextRun({
                      text: m.label.toUpperCase(),
                      bold: true,
                      color: COLORS.ink3,
                      size: 16,
                    }),
                  ],
                }),
                new Paragraph({
                  children: [
                    new TextRun({
                      text: m.value,
                      bold: true,
                      color: COLORS.navy,
                      size: 22,
                    }),
                  ],
                }),
              ],
            }),
        ),
      }),
    ],
  })
}

function simpleTable(
  headers: string[],
  rows: string[][],
  widthPct: number[],
): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: {
      top: { style: BorderStyle.SINGLE, size: 4, color: COLORS.line },
      bottom: { style: BorderStyle.SINGLE, size: 4, color: COLORS.line },
      left: { style: BorderStyle.SINGLE, size: 4, color: COLORS.line },
      right: { style: BorderStyle.SINGLE, size: 4, color: COLORS.line },
      insideHorizontal: {
        style: BorderStyle.SINGLE,
        size: 2,
        color: COLORS.line,
      },
      insideVertical: {
        style: BorderStyle.SINGLE,
        size: 2,
        color: COLORS.line,
      },
    },
    rows: [
      new TableRow({
        tableHeader: true,
        children: headers.map(
          (h, i) =>
            new TableCell({
              width: { size: widthPct[i], type: WidthType.PERCENTAGE },
              shading: {
                type: ShadingType.CLEAR,
                color: 'auto',
                fill: COLORS.teal,
              },
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: h.toUpperCase(),
                      bold: true,
                      color: 'FFFFFF',
                      size: 17,
                    }),
                  ],
                }),
              ],
            }),
        ),
      }),
      ...rows.map(
        (row) =>
          new TableRow({
            children: row.map(
              (cell, i) =>
                new TableCell({
                  width: { size: widthPct[i], type: WidthType.PERCENTAGE },
                  children: [
                    new Paragraph({
                      children: inlineChildren(cell, {
                        size: 19,
                        color: i === 0 ? COLORS.navy : COLORS.ink2,
                        bold: i === 0,
                      }),
                    }),
                  ],
                }),
            ),
          }),
      ),
    ],
  })
}

function inlineChildren(
  md: string,
  runOpts: { size?: number; color?: string; bold?: boolean } = {},
): Array<TextRun | ExternalHyperlink> {
  const size = runOpts.size ?? 22
  const color = runOpts.color ?? COLORS.ink2
  const baseBold = runOpts.bold ?? false
  return parseInline(md).map((tok) => {
    if (tok.kind === 'link') {
      return new ExternalHyperlink({
        link: tok.href,
        children: [
          new TextRun({
            text: tok.value,
            size,
            color: COLORS.teal,
            underline: {},
          }),
        ],
      })
    }
    const bold = baseBold || tok.kind === 'strong'
    const italics = tok.kind === 'em'
    return new TextRun({ text: tok.value, size, color, bold, italics })
  })
}

function stripTrailingPeriod(s: string): string {
  return s.endsWith('.') ? s.slice(0, -1) : s
}
