import { createClient } from '@supabase/supabase-js'
import { notFound } from 'next/navigation'
import { composePrivacyNotice } from '@consentshield/compliance'

// Public privacy notice page — no auth required. Backed by rpc_get_privacy_notice
// (anon-granted security-definer RPC owned by cs_orchestrator). See ADR-0009.

interface PrivacyEnvelope {
  ok: boolean
  error?: string
  org?: { name: string; compliance_contact_email: string | null; dpo_name: string | null }
  inventory?: Array<{
    data_category: string
    collection_source: string | null
    purposes: string[]
    legal_basis: string
    retention_period: string | null
    third_parties: string[]
    data_locations: string[]
  }>
}

export default async function PrivacyNoticePage({
  params,
}: {
  params: Promise<{ orgId: string }>
}) {
  const { orgId } = await params

  const anon = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  )

  const { data } = await anon.rpc('rpc_get_privacy_notice', { p_org_id: orgId })
  const envelope = data as PrivacyEnvelope | null

  if (!envelope?.ok || !envelope.org) notFound()

  const sections = composePrivacyNotice(envelope.org, envelope.inventory ?? [])

  return (
    <main className="max-w-3xl mx-auto px-6 py-12">
      <header className="mb-8 pb-6 border-b border-gray-200">
        <h1 className="text-3xl font-bold">Privacy Notice</h1>
        <p className="mt-2 text-sm text-gray-600">
          {envelope.org.name} · Compliant with the Digital Personal Data Protection Act 2023
        </p>
      </header>

      <article className="space-y-8">
        {sections.map((section, i) => (
          <section key={i}>
            <h2 className="text-lg font-semibold mb-2">
              {i + 1}. {section.heading}
            </h2>
            <div className="text-sm text-gray-700 whitespace-pre-line leading-relaxed">
              {section.body}
            </div>
          </section>
        ))}
      </article>

      <footer className="mt-12 pt-6 border-t border-gray-200 text-xs text-gray-500">
        <p>
          This notice was generated by ConsentShield. Visit{' '}
          <a
            href="https://consentshield.in"
            className="underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            consentshield.in
          </a>{' '}
          for more information.
        </p>
      </footer>
    </main>
  )
}
